var tableauQuestion = [
    {   question : " Vad blir konsekvensen av att styrservon är ur funktion?",
        propositionA : "Bilen går att styra, men det är mycket tyngre",
        propositionB : "Bilen går inte att styra",
        propositionC : "Bilen blir understyrd",
        propositionD : "Bilen blir överstyrd",
        reponse : "A"},

    {   question : "Vad är sant angående krockkudde?",
        propositionA : "Den utlöses alltid vid kollisioner",
        propositionB : "Krockkudde får inte användas i kombination med säkerhetsbälte",
        propositionC : "Man bör inte sitta närmare än 25 cm från krockkudden",
        propositionD : "Barn skyddas bäst om de sitter i en bilbarnstol vid en plats som har krockkudde",
        reponse : "C"},

    {   question : "Vad är sant angående den gula markeringen på trottoarkanten?",
        propositionA : "Jag får parkera här men högst i 24 timmar",
        propositionB : "Jag får parkera här men bilens hjul får inte stå på trottoarkanten",
        propositionC : "Jag får stanna men inte parkera här",
        propositionD : "Jag får inte parkera eller stanna här",
        reponse : "C"},

  {   question : "Vad är den största fördelen med biobränsle jämfört med fossilt bränsle?",
        propositionA : "Växthuseffekten påverkas inte",
        propositionB : "Motorprestandan blir bättre",
        propositionC : "Slitaget på motorn blir mindre",
        propositionD : "Motorns delar smörjs och därmed minskar utsläppen",
        reponse : "A"},

  {   question : "När ska du använda varningsblinkers?",
        propositionA : "När jag stannat vid en busshållplats för att släppa av en passagerare",
        propositionB : "När jag har fått motorstopp och utgör fara för andra fordon",
        propositionC : "När jag parkerat på en huvudled",
        propositionD : "När jag får panik",
        reponse : "B"},

  {   question : "Vad menas med reaktionssträcka?",
        propositionA : "Den sträcka bilen färdas från det att jag börjar bromsa tills bilen står still",
        propositionB : "Den sträcka bilen färdas från det att jag uppfattar en fara tills jag hinner reagera",
        propositionC : "Den tid det tar för mig att reagera",
        propositionD : "Den tiden det dar om du bränner dig på en stekpanna innan den kommer fram till hjärnan",
        reponse : "B"},

  {   question : "Du är på väg att köra in på motorvägen, vad är sant?",
        propositionA : "Jag ska kraftigt öka min hastighet för att underlätta påfarten",
        propositionB : "Jag måste lämna företräde till alla fordon på motorvägen",
        propositionC : "Alla fordon på motorvägen måste lämna mig företräde",
        propositionD : "Du får köra hur snabbt du vill",
        reponse : "A"},

  {   question : "Framför dig kör ett fordon med LGF-skylt. Vilken är den högsta hastighet som fordonet får köra?",
        propositionA : "30 km/h",
        propositionB : "40 km/h",
        propositionC : "45 km/h",
        propositionD : "60 km/h",
        reponse : "C"},

  {   question : " I vilken situation gäller högerregeln?",
        propositionA : "Jag kör ut från en bensinstation",
        propositionB : "Jag kör på en huvudled och kommer till en korsning",
        propositionC : "Jag kommer till en korsning i ett tättbebyggt område utan anvisningar",
        propositionD : "Jag kör ut från en parkering",
        reponse : "C"},

  {   question : "Vad ska du göra om du hamnar i kö?",
        propositionA : "Jag ska alltid hålla samma avstånd till fordonet framför mig",
        propositionB : "Jag ska stanna på så sätt att jag inte hindrar korsande trafik",
        propositionC : "Jag ska stanna så nära framförvarande fordon som möjligt så att kön blir kortare",
        propositionD : "Jag ska sätta på varningsblinkers så bilar bakom vet att det är kö",
        reponse : "B"},
]
